### PR TITLE
Adding solution to challenge 4

### PR DESCRIPTION
**Pull request by JBeatz**
Sorry to spam with requests, please excuse the Git teething problems! As before:

This is based on the solution I have made to challenge 3, so is unlikely to be used. However I thought it may be nice to look over, as it seems to work pretty well! Code is commented, but variable names/function names are still in their "creation" phase, so do pardon them! haha

I hope I am requesting this to the correct base! The request is more to bring it to your attention that I have completed the challenge and for potential inspiration to others, rather than something I think will actually be merged!

### CODE REVIEW

**Comment by robplee** [comment]
Thanks for the pull request.  I was wanting to take a look at your code and was thinking of sending you a message about it!  I have a couple of general comments but I haven't had much chance to take a look.

Firstly, you didn't need to implement your own hex string input functions, xor function and file reading.  If you look in cpp/util/ you'll find MatasanoConverters.cpp, MatasanoUtil.cpp and FileRead.cpp these contain functions that will do the string reading/converting, xor-ing of vector<uint8_t> and a function called ReadFileContents that you give a filename and it'll convert it into a vector of strings (exactly like your readfile function does).

Secondly, in StringTesting.cpp/.h there is already a function that takes a vector of TestStrings (which is just a struct to combine score, key and decrypted string together) and it does what I think your keytest does.

The other thing I've spotted so far is that your code looks different to mine.  I know this is petty but I think it would be good practice for us to try to stick to the same sort of styling.  I'm not sure what normal C++ best practice is but I have been following this guide https://google.github.io/styleguide/cppguide.html

I'll have another look later but I have a meeting right now so I can't give any other feedback!

**Comment by robplee** [comment]
I've had another look and I'm a bit confused by your use of vector<char> with your keytest function.  Couldn't you have just used string?  Strings aren't actually all that bad in C++ as you can append quite easily e.g.

```
string s = "hello";
cout << s << endl;
s.append(" world");
cout << s << endl;
s += "!";
cout << s << endl;
```

Will print:

```
hello
hello world
hello world!
```

Finding the length of a string is quite easy too as you can use .size() or .length().  Was there a particular reason you used a vector instead of a string?

Also, I think we discussed that in the files that contain the string testing code (StringTesting.cpp and StringTesting.h) there is a struct defined called TestString.  I added that and made my string testing functions use it as then we can store, with a decrypted string what the score and key for that string are.  If you our code uses something like that then it will be easier to keep track of what the most likely key is but also what the score it received from the frequency analysis was.

I would like to emphasis that your code does look good and I'm sure it solves the challenge.  I'm just making comments that I think might improve the style or allow your solution to fit in with the code we already have.  If we build up a set of functions then I think we'll have a lot of our work on future tasks done for us before we start and then we can focus on the new things knowing that we have great code for what we've already done.

**Comment by JBeatz** [comment]
Thanks for your feedback!

I think I began writing using strings, but after some memory allocation issues I decided to stick to vectors, for no other reason than I found them easier to work with.

The reason I wrote my own hex encode functions etc. was because I was unsure how to import functions in Visual Studio/c++ so had to make my own to continue. I also quite like the idea of having the whole challenges complete with all my own code as well as the group activity, to fully make sure I understand it! ahah.

And yes, I'm aware the formatting of names etc. sucks, I wasn't planning on contributing any of this when I first wrote it. So I apologise for the perhaps misleading and out of style syntax!

I also agree with you idea of using a structure, this is something I haven't coded in a long time, so kind of forgot about! Its a much better way of storing the "meta-data" associated with the strings!

Thanks again for taking a look, I appreciate it!

**Comment by robplee** [comment]
I've done this with a separate PR as I didn't want to pull into my regular master branch.

**Pull request closed without merging**
